name: Run tests
on:
  push:
  pull_request:
    branches: [ master ]
jobs:
    test:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python: ["3.6", "3.7", "3.8", "3.9", "3.10"]
      steps:
        - uses: actions/checkout@v2
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python }}
        - name: Install Tox and any other packages
          run: |
            python -m pip install --upgrade pip
            pip install tox tox-gh-actions
        - name: Run Tox
          run: tox -epy
    flake8:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: "3.10"
        - name: Install Tox and any other packages
          run: |
            python -m pip install --upgrade pip
            pip install tox tox-gh-actions
        - name: Lint with flake8
          run: tox -eflake8
    integration:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: "3.10"
        - name: Install Tox and any other packages
          run: |
            python -m pip install --upgrade pip
            pip install tox tox-gh-actions
        - name: Run integration tests
          run: tox -eintegration
